### PR TITLE
DLPX-72206 ZFS package build does not fail when warnings occur

### PR DESCRIPTION
**Pull request by pzakha**
This turns on `-Werror` for all ZFS builds regardless of whether `--with-debug` is set.

I think this is something that would benefit from being upstreamed as well, but I wanted to open it internally first so that we could discuss it.

## Testing
- ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4156/
- ab-pre-push that catches a warning in ZFS (uses the same bits that DLPX-72206 was opened for): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4157/

### CODE REVIEW

**Comment by prakashsurya** [comment]
Can we propose this upstream before we commit to it downstream only? I'd like to get feedback from upstream, since I feel like it might be a good change there too.

**Review by prakashsurya — APPROVED** [review]
LGTM.

**Comment by pzakha** [comment]
I've opened https://github.com/openzfs/zfs/pull/11058 upstream

**Comment by pzakha** [comment]
I've closed the upstream PR, so we can proceed with this one.
cc: @ahrens

**Review by ahrens — APPROVED** [review]

**Pull request merged**
