### PR TITLE
WIP: Bring 6.0/stage up to date with master

### PR DESCRIPTION
**Pull request by sdimitro**
= Steps

1] `git merge`'d the master branch and for merge conflicts picked everything from master
2] doing a `git diff` against master I see the following:
```
$ git diff delphix/master
diff --git a/module/zfs/btree.c b/module/zfs/btree.c
index 72f7c28224..0a1283e0a6 100644
--- a/module/zfs/btree.c
+++ b/module/zfs/btree.c
@@ -1469,7 +1469,7 @@ zfs_btree_remove_from_node(zfs_btree_t *tree, zfs_btree_core_t *node,
        /*
         * In this case, neither of our neighbors can spare an element, so we
         * need to merge with one of them. We prefer the left one,
-        * arabitrarily. Move the separator into the leftmost merging node
+        * arbitrarily. Move the separator into the leftmost merging node
         * (which may be us or the left neighbor), and then move the right
         * merging node's elements. Once that's done, we go back and delete
         * the element we're removing. Finally, go into the parent and delete
@@ -1711,7 +1711,7 @@ zfs_btree_remove_idx(zfs_btree_t *tree, zfs_btree_index_t *where)
        /*
         * In this case, neither of our neighbors can spare an element, so we
         * need to merge with one of them. We prefer the left one,
-        * arabitrarily. Move the separator into the leftmost merging node
+        * arbitrarily. Move the separator into the leftmost merging node
         * (which may be us or the left neighbor), and then move the right
         * merging node's elements. Once that's done, we go back and delete
         * the element we're removing. Finally, go into the parent and delete
```
3] I rechecked all the history from `6.0/stage` and re-applied and skipped some patches as I saw fit - below is all the info

- Commits that I examined manually from the 6.0/stage branch and required no change:

86faae616ce32bb768441087605fa40cb93091b8 Disable "-fipa-sra" when using "--enable-debuginfo" (#127)
129d75d550d01b6893e3de495894920e407a2eac Fix mismerged mem limit for range trees (#130)
6fa695381fa2cb7fb7583aa9108839fa2254a18f DLPX-68523 [Backport of DLPX-68522 to 6.0.1.0] Remove limit on number of async zio_frees of non-dedup blocks
f30abc5aab80001c80bfa589f1fc7c14e1e36301  DLPX-68046 [Backport of Issue DLPX-65948 to 6.0.1.0] incrementalSendReceiveTest failed due to "DelphixFatalException: unexpected ZFS error: EBUSY on..."
cd62d32b6c2ee9b936d4c3d4824d922a0ab812ec DLPX-69204 [Backport of DLPX-69203 to 6.0.1.1] Improve ZVOL sync write performance by using a taskq (#144)
3784229b166470d1bae553f6afbdc0cc09007bbf ZTS: devices_001_pos and devices_002_neg (#142)
f75dea29b3ac9a4d63017e6c8fc41b4896a8bc22 Update skc_obj_alloc for spl kmem caches that are backed by Linux (#138)
5db3bc0b40eec529d368e8e0c1cf359233b17c28 Name anonymous enum of KMC_BIT constants (#136)
52e787593730365b992c3f93b35b45d1f608e358 DLPX-69007 [Backport of DLPX-69006 to 6.0.2.0] SIMD: Use alloc_pages_node to force alignment (#140)
79419fa935b0bc83f274d65a201dd16309541d7e DLPX-68992 [Backport of DLPX-68991 to 6.0.2.0] Fix zpool history unbounded memory usage (#139)
ae806e7a97a7c4e9bd814d2b44be0ee22d77b0d1 ZFS performance suite should use JSON fio output (#147)
6aced2e2ee6ffdfa3469aed9a8bb94382da74b7f Don't call arc_buf_destroy on unallocated arc_buf (#148)
f36890feaa0f59c2e09beb300f6ef6542dff69fb DLPX-68998 [Backport of DLPX-68997 to 6.0.3.0] Improve performance of zio_taskq_member
df4edd690328a1e72d449ea5d0c974397e34bd6e DLPX-68996 [Backport of DLPX-68995 to 6.0.3.0] Improve zfs destroy performance with zio_t-free zio_free()
31aedb9df116d4ac0de23316c81bd0adabd0f976 Revert "Update skc_obj_alloc for spl kmem caches that are backed by Linux (#138)" (#161)
c4c9b0d8c9d0043e13a4058cb53b8ebc7fa13256 Split debug info of ZFS modules to separate package (#154) (#160)
f30409a252d8049dbedd1eced92ca908afb01c63 DLPX-69058 [Backport of DLPX-69057 to 6.0.3.0] Improve zfs receive performance by batching writes
1faff4c156923a7d029338e8ad08f6c5f4ea3434 Running `make install` should split debug info (#166)
1662833877902a898262ebeb7fb5a3856ffc6d78 DLPX-69940 [Backport of DLPX-69914 to 6.0.2.1] disable automatic scrubs (#171)
b31d00d91ee61c57b46a6a1d970a32a8f676ddb2 DLPX-69000 [Backport of DLPX-68999 to 6.0.3.0] Improve zfs send performance by bypassing the ARC
e9ffc36f7423cd9b851e3b5fb449365f017caeb0 DLPX-70086 [Backport of DLPX-70004 to 6.0.3.0] domain0 inaccessible after GPF during device removal run
74e32987efb8fc6f97bf623f66b9252ac30c65ad Fix error handling in receive_writer_thread()
613fcfbca0143c63304b83505a736f33ce33485e DLPX-70698 [Backport of DLPX-70697 to 6.0.3.0] Prevent zfs memory reaping logic from running by capping zfs_arc_max (#176)
f44d3dac5d173abdda5dd2e7a5ea19373834f6f9 [Backport of DLPX-70703 to 6.0.3.0] arc shrinking stalls allocations
24760197329bf635af0f35c4bcb8780e10f36003 arcstat: add 'avail', fix 'free'
17473a1c680fcbfca1637a7db3aafdbca5a013ba Linux compat: Minimum kernel version 3.10
0438cddacebe37b8ef6ad5c4a6498990d495df56 Revise SPL wrapper for shrinker callbacks
e34c320582c34ef65c9ef15dad7b78f1d2f3f187 anon_pages are not free/evictable
ed32cbbc1f04db042bc7726784632d8ef32fb3e9 Adjust ARC terminology
ec6716fa6c6cf5b7a4098ab6a594de7668bce975 Revert "DLPX-70698 [Backport of DLPX-70697 to 6.0.3.0] Prevent zfs memory reaping logic from running by capping zfs_arc_max (#176)"
416a29f80c37c540ba8cf43eadb154549f9fa82d DLPX-68691 [Backport of DLPX-68690 to 6.0.4.0] Scalable NFS sharing of ZFS filesystems (#188)
1b91a2294498ac907ef519c80ef99b63b956f3b1 ZTS: Fix zpool_reopen_001_pos
77528deff5ae5be165975569bdc83a01a74ab3c3 DLPX-70838 [Backport of DLPX-61344 to 6.0.4.0] Need mechanism from ZFS to wait for the delete queue to drain (#191)
1c97373ee6cc27af46e71fd519d3170a084d4e0d DLPX-71272 [Backport of DLPX-71270 to 6.0.4.0] zfs promote does not delete livelist of origin
e9b19e5a2be2e3f2f481c6fad119f2b38b1e14ee DLPX-71119 [Backport of DLPX-71118 to 6.0.4.0] Remove skc_reclaim, hdr_recl, kmem_cache shrinker
91ace51d1725558d93ad39429d23d09bbe19a316 ZTS: Backport changes eliminating partitioning (#198)
5c3214b774b468dbc953f45dc98877c92b5d8c29 DLPX-71354 [Backport of DLPX-71313 to 6.0.4.0] Oracle VDB becomes inactive during deferred upgrades from 6.0.3.0 (#204)

- Patches that were part of 6.0/stage that I skipped:

e6dd877df63cd169b7db548f2fc9768c378598a2 Fixes for zfs wait backport

- Patches that I had to re-apply and re-adjust in the merge commit:

37bb1ae36cdad594d9d4285466847bbe9c0fa660 Add tunable to make all zvol writes sync when sync=standard
5eeb595be6600da344c13f650facccb3fbd5f30f DLPX-69299 [Backport of DLPX-69298 to 6.0.1.1] Data corruption after DE reboot if zfs sync=standard on zvols

- Patches that I had to partially re-apply:

0036a88b1e81edc424ab2292f67cad0757e3dcf6 Revise ARC shrinker algorithm
67efdeac109bea1716ad9cc90a8f1d131fb7721f ARC waiters must wait for sufficient free memory

All the re-applied changes together can be found on the following diff with master:
```
diff --git a/include/os/linux/zfs/sys/trace_arc.h b/include/os/linux/zfs/sys/trace_arc.h
index 3df491f8b3..54c87cc515 100644
--- a/include/os/linux/zfs/sys/trace_arc.h
+++ b/include/os/linux/zfs/sys/trace_arc.h
@@ -411,9 +411,9 @@ DEFINE_DTRACE_PROBE1(l2arc__miss);
 DEFINE_DTRACE_PROBE2(l2arc__read);
 DEFINE_DTRACE_PROBE2(l2arc__write);
 DEFINE_DTRACE_PROBE2(l2arc__iodone);
-DEFINE_DTRACE_PROBE3(arc__wait__for__eviction);
 DEFINE_DTRACE_PROBE4(arc__miss);
 DEFINE_DTRACE_PROBE4(l2arc__evict);
+DEFINE_DTRACE_PROBE4(arc__wait__for__eviction);
 
 #endif /* HAVE_DECLARE_EVENT_CLASS */
 #endif /* _KERNEL */
diff --git a/include/sys/arc_impl.h b/include/sys/arc_impl.h
index bb9163ba79..5665ff46c8 100644
--- a/include/sys/arc_impl.h
+++ b/include/sys/arc_impl.h
@@ -823,7 +823,6 @@ typedef struct arc_stats {
 	kstat_named_t arcstat_l2_rebuild_log_blks;
 	kstat_named_t arcstat_memory_throttle_count;
 	kstat_named_t arcstat_memory_direct_count;
-	kstat_named_t arcstat_memory_indirect_count;
 	kstat_named_t arcstat_memory_all_bytes;
 	kstat_named_t arcstat_memory_free_bytes;
 	kstat_named_t arcstat_memory_available_bytes;
diff --git a/module/os/linux/zfs/arc_os.c b/module/os/linux/zfs/arc_os.c
index d0e57ced06..16bfd3715d 100644
--- a/module/os/linux/zfs/arc_os.c
+++ b/module/os/linux/zfs/arc_os.c
@@ -231,17 +231,7 @@ arc_shrinker_scan(struct shrinker *shrink, struct shrink_control *sc)
 	 */
 	arc_no_grow = B_TRUE;
 
-	/*
-	 * When direct reclaim is observed it usually indicates a rapid
-	 * increase in memory pressure.  This occurs because the kswapd
-	 * threads were unable to asynchronously keep enough free memory
-	 * available.
-	 */
-	if (current_is_kswapd()) {
-		ARCSTAT_BUMP(arcstat_memory_indirect_count);
-	} else {
-		ARCSTAT_BUMP(arcstat_memory_direct_count);
-	}
+	ARCSTAT_BUMP(arcstat_memory_direct_count);
 
 	return (sc->nr_to_scan);
 }
@@ -307,46 +297,21 @@ arc_lowmem_init(void)
 	 * arc_wait_for_eviction() will wait until at least the
 	 * high_wmark_pages() are free (see arc_evict_state_impl()).
 	 *
-	 * Note: Even when the system is very low on memory, the kernel's
-	 * shrinker code may only ask for one "batch" of pages (512KB) to be
-	 * evicted.  If concurrent allocations consume these pages, there may
-	 * still be insufficient free pages, and the OOM killer takes action.
-	 *
-	 * By setting arc_sys_free large enough, and having
-	 * arc_wait_for_eviction() wait until there is at least arc_sys_free/2
-	 * free memory, it is much less likely that concurrent allocations can
-	 * consume all the memory that was evicted before checking for
-	 * OOM.
-	 *
 	 * It's hard to iterate the zones from a linux kernel module, which
 	 * makes it difficult to determine the watermark dynamically. Instead
-	 * we compute the maximum high watermark for this system, based
-	 * on the amount of memory, assuming default parameters on Linux kernel
-	 * 5.3.
-	 */
-
-	/*
-	 * Base wmark_low is 4 * the square root of Kbytes of RAM.
-	 */
-	long wmark = 4 * int_sqrt(allmem/1024) * 1024;
-
-	/*
-	 * Clamp to between 128K and 64MB.
-	 */
-	wmark = MAX(wmark, 128 * 1024);
-	wmark = MIN(wmark, 64 * 1024 * 1024);
-
-	/*
-	 * watermark_boost can increase the wmark by up to 150%.
-	 */
-	wmark += wmark * 150 / 100;
-
-	/*
-	 * arc_sys_free needs to be more than 2x the watermark, because
-	 * arc_wait_for_eviction() waits for half of arc_sys_free.  Bump this up
-	 * to 3x to ensure we're above it.
+	 * we consider the maximum high watermark for any system, assuming
+	 * default parameters on Linux kernel 5.3.  The maximum low watermark
+	 * is 64MB, the max high watermark is 64MB + 0.2% of RAM, and the
+	 * maximum boost is 150% of the high watermark.  So the maximum
+	 * boosted high watermark is 160MB + 0.5% of RAM.
+	 *
+	 * The default arc_sys_free is 512MB + 1/32nd (3%) of RAM, which is
+	 * more than double the highest high_wmark (160MB + 0.5% of RAM).
+	 * Note that the extra 512MB is only strictly necessary on systems
+	 * with less than 16GB of RAM, but we always add it as an extra
+	 * cushion.
 	 */
-	arc_sys_free = wmark * 3 + allmem / 32;
+	arc_sys_free = 512 * 1024 * 1024 + allmem / 32;
 }
 
 void
diff --git a/module/os/linux/zfs/zvol_os.c b/module/os/linux/zfs/zvol_os.c
index 7767499640..38f100b3ff 100644
--- a/module/os/linux/zfs/zvol_os.c
+++ b/module/os/linux/zfs/zvol_os.c
@@ -46,6 +46,12 @@ unsigned int zvol_request_sync = 0;
 unsigned int zvol_prefetch_bytes = (128 * 1024);
 unsigned long zvol_max_discard_blocks = 16384;
 unsigned int zvol_threads = 32;
+/*
+ * Delphix: Make all zvol writes and discards sync unless sync=disabled
+ * is set. This is meant to avoid data corruption when exposing the zvols
+ * over iSCSI and the system reboots unexpectedly.
+ */
+unsigned int zvol_sync_by_default = 1;
 
 /*
  * This flag is specific to the Delphix product.  It always exports a phys
@@ -133,8 +139,10 @@ zvol_write(void *arg)
 	blk_generic_start_io_acct(zv->zv_zso->zvo_queue, WRITE,
 	    bio_sectors(bio), &zv->zv_zso->zvo_disk->part0);
 
-	boolean_t sync =
-	    bio_is_fua(bio) || zv->zv_objset->os_sync == ZFS_SYNC_ALWAYS;
+	boolean_t sync = bio_is_fua(bio) ||
+	    zv->zv_objset->os_sync == ZFS_SYNC_ALWAYS ||
+	    (zvol_sync_by_default &&
+	    zv->zv_objset->os_sync == ZFS_SYNC_STANDARD);
 
 	zfs_locked_range_t *lr = zfs_rangelock_enter(&zv->zv_rangelock,
 	    uio.uio_loffset, uio.uio_resid, RL_WRITER);
@@ -202,7 +210,9 @@ zvol_discard(void *arg)
 	blk_generic_start_io_acct(zv->zv_zso->zvo_queue, WRITE,
 	    bio_sectors(bio), &zv->zv_zso->zvo_disk->part0);
 
-	sync = bio_is_fua(bio) || zv->zv_objset->os_sync == ZFS_SYNC_ALWAYS;
+	sync = bio_is_fua(bio) || zv->zv_objset->os_sync == ZFS_SYNC_ALWAYS ||
+	    (zvol_sync_by_default &&
+	    zv->zv_objset->os_sync == ZFS_SYNC_STANDARD);
 
 	if (end > zv->zv_volsize) {
 		error = SET_ERROR(EIO);
@@ -1120,6 +1130,10 @@ MODULE_PARM_DESC(zvol_threads, "Max number of threads to handle I/O requests");
 module_param(zvol_request_sync, uint, 0644);
 MODULE_PARM_DESC(zvol_request_sync, "Synchronously handle bio requests");
 
+module_param(zvol_sync_by_default, uint, 0644);
+MODULE_PARM_DESC(zvol_sync_by_default,
+       "For zvols treat sync=standard as sync=always");
+
 module_param(zvol_max_discard_blocks, ulong, 0444);
 MODULE_PARM_DESC(zvol_max_discard_blocks, "Max number of blocks to discard");
 
diff --git a/module/zfs/arc.c b/module/zfs/arc.c
index 850c435034..682ee0bea3 100644
--- a/module/zfs/arc.c
+++ b/module/zfs/arc.c
@@ -563,7 +563,6 @@ arc_stats_t arc_stats = {
 	{ "l2_rebuild_log_blks",	KSTAT_DATA_UINT64 },
 	{ "memory_throttle_count",	KSTAT_DATA_UINT64 },
 	{ "memory_direct_count",	KSTAT_DATA_UINT64 },
-	{ "memory_indirect_count",	KSTAT_DATA_UINT64 },
 	{ "memory_all_bytes",		KSTAT_DATA_UINT64 },
 	{ "memory_free_bytes",		KSTAT_DATA_UINT64 },
 	{ "memory_available_bytes",	KSTAT_DATA_INT64 },
@@ -5105,7 +5104,8 @@ arc_wait_for_eviction(uint64_t amount)
 
 			arc_set_need_free();
 
-			DTRACE_PROBE3(arc__wait__for__eviction,
+			DTRACE_PROBE4(arc__wait__for__eviction,
+			    arc_evict_waiter_t *, &aw,
 			    uint64_t, amount,
 			    uint64_t, arc_evict_count,
 			    uint64_t, aw.aew_count);
diff --git a/module/zfs/btree.c b/module/zfs/btree.c
index 72f7c28224..0a1283e0a6 100644
--- a/module/zfs/btree.c
+++ b/module/zfs/btree.c
@@ -1469,7 +1469,7 @@ zfs_btree_remove_from_node(zfs_btree_t *tree, zfs_btree_core_t *node,
 	/*
 	 * In this case, neither of our neighbors can spare an element, so we
 	 * need to merge with one of them. We prefer the left one,
-	 * arabitrarily. Move the separator into the leftmost merging node
+	 * arbitrarily. Move the separator into the leftmost merging node
 	 * (which may be us or the left neighbor), and then move the right
 	 * merging node's elements. Once that's done, we go back and delete
 	 * the element we're removing. Finally, go into the parent and delete
@@ -1711,7 +1711,7 @@ zfs_btree_remove_idx(zfs_btree_t *tree, zfs_btree_index_t *where)
 	/*
 	 * In this case, neither of our neighbors can spare an element, so we
 	 * need to merge with one of them. We prefer the left one,
-	 * arabitrarily. Move the separator into the leftmost merging node
+	 * arbitrarily. Move the separator into the leftmost merging node
 	 * (which may be us or the left neighbor), and then move the right
 	 * merging node's elements. Once that's done, we go back and delete
 	 * the element we're removing. Finally, go into the parent and delete
```

= Testing

- compiled and loaded bits in a VM which seems to be running file
- zfs-test (pending): http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5433/
- ab-pre-push (pending): http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/3896/

### CODE REVIEW

**Comment by ahrens** [comment]
Thanks for taking a thorough look at this.  Most if not all of the diffs that we want to have in 6.0 (compared to master) should probably also be applied to master.  We might want to handle this by applying them on master before doing this merge, to minimize the diffs between 6.0 and master.

e6dd877 Fixes for zfs wait backport
It looks like the change to `linux.run` is still needed?

37bb1ae Add tunable to make all zvol writes sync when sync=standard
5eeb595 DLPX-69299 [Backport of DLPX-69298 to 6.0.1.1] Data corruption after DE reboot if zfs sync=standard on zvols
These seem particularly important to have on master.

0036a88 Revise ARC shrinker algorithm
67efdea ARC waiters must wait for sufficient free memory
`arcstat_memory_indirect_count` should probably be applied upstream and to master?
`arc_lowmem_init` changes should probably be applied to master

Typo fixes in `btree.c` should be applied upstream and to master.

**Comment by sdimitro** [comment]
Opened typo fixes for btree.c upstream here -> https://github.com/openzfs/zfs/pull/10725

**Comment by sdimitro** [comment]
Opened PR for zvol sync patch here -> https://github.com/delphix/zfs/pull/206

**Comment by sdimitro** [comment]
Opened PR for `arc_lowmem_init` changes on master here -> https://github.com/delphix/zfs/pull/207

**Comment by sdimitro** [comment]
Closing due to https://github.com/delphix/zfs/pull/217

**Pull request closed without merging**
