### PR TITLE
Merge 07 jun

### PR DESCRIPTION
**Pull request by jwk404**
### Motivation and Context

Resolving merge and build failures to get automation back on track.

### Description

This set of changes had conflicts in man/man5/zpool-features.5 and
lib/libzfs_core/libzfs_core.abi. The manpage conflict was due to the
section for the livelist feature being included twice in our copy, so I
deleted the extra. The abi change was due to 94f942c6. Neither version
of this abi file could pass `make checkabi` so I generated a new one
with `make storeabi`.

This revealed that `make storeabi` was broken locally due to the
absence of an include in `lib/libzfsbootenv/Makefile.am`.

This revealed that two functions in `include/libzfs.h`
(zfs_get_hole_count and zfs_get_access_info) needed to be declared with
default visibility. Neither exist upstream, which is why their
visibility was not updated upstream in 739cfb96. This also necessitated
including an updated `lib/libzfs/libzfs.api`.

### How Has This Been Tested?

Manually ran `make checkabi` and `make storeabi` in built tree.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5456/ (in progress)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by sebroy — APPROVED** [review]

**Comment by ahrens** [comment]
I thought that we took upstream's .api files, to avoid merge conflicts, and then we ignore the api checks on our branch.

**Comment by jwk404** [comment]
Looking at the checks for this PR, it seems like the abi checks are run as part of checkstyle. I could take the upstream abi files and update `.github/workflows/checkstyle.yaml` to not install the abi tools and make that target?

**Comment by ahrens** [comment]
Yeah, not running the abi checks on our branch makes sense.  The problem with regenerating the abi files is that since it doesn't happen automatically, every api update will be a merge conflict.

**Comment by jwk404** [comment]
Took abi files from openzfs master and removed abi checks from checkstyle. New tests (still running):
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5458/

**Review by pzakha — APPROVED** [review]

**Pull request merged**
