### PR TITLE
Addition of ZFS tests in tests/runfiles/object_store.run

### PR DESCRIPTION
**Pull request by ankurs-delphix**
Addition of ZFS tests in the object_store.run

### Motivation and Context

This is in continuation of the object storage support in ZFS, wherein we are expanding our testcoverage. 
### Description

This review request contains existing testcases which has been tested against the object storage & thus they have been added to the object_store.run file

-   DOSE-382 Zfs
-   DOSE-383 Zfs_bookmark
-   DOSE-384 Zfs_change-key
-   DOSE-301 Chattr tests
-   DOSE-307 Cp_files tests
-   DOSE-308 Ctime tests
-   DOSE-294 Atime tests
-   DOSE-315 Exec tests
-   DOSE-316 Fallocate tests
-   DOSE-336 Mount tests
-   DOSE-366 Suid tests

This also contains a fix in the script `zfs-tests.sh` to cleanup `zfs_object_agent` process which remains in the system even when test completes.

### How Has This Been Tested?

- Deployed my changes to the VM based on dlpx-dose
- Set required enviroment variables to enable S3 object storage
  - ZTS_BUCKET_NAME=cloudburst-data-2
  - ZTS_REGION=us-west-2
  - ZTS_OBJECT_ENDPOINT=https://s3-us-west-2.amazonaws.com
  - ZTS_OBJECT_STORE=true
- Triggered independent tests with 
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T zfs
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T zfs_bookmark
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T zfs_change-key
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T chattr
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T cp_files
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T ctime
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T atime
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T exec
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T fallocate
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T mount
  - /usr/share/zfs/zfs-tests.sh -r object_store.run -T suid

### CODE REVIEW

**Review by nupur-agrawal-delphix — APPROVED** [review]
Great work Ankur !

**Comment by ahrens** [comment]
I would guess that `/usr/share/zfs/zfs-tests.sh -r object_store.run` (i.e. run all the tests in that runfile) also works?

Do you have any thoughts on how to run these tests automatically?  E.g. with `git zfs-precommit` (jenkins) and/or a github action (see .github/workflows/zfs-tests-sanity.yml for an example), if we can figure out how to do that without exposing our S3 secret keys (e.g. by using minio rather than S3, or some sort of github secret management).

**Comment by nupur-agrawal-delphix** [comment]
> I would guess that `/usr/share/zfs/zfs-tests.sh -r object_store.run` (i.e. run all the tests in that runfile) also works?
Yes we can run the tests from object_store.run file.

> Do you have any thoughts on how to run these tests automatically? E.g. with `git zfs-precommit` (jenkins) and/or a github action (see .github/workflows/zfs-tests-sanity.yml for an example), if we can figure out how to do that without exposing our S3 secret keys (e.g. by using minio rather than S3, or some sort of github secret management).
We have been working on getting github actions working for object store run. We are planning to use github secret management for now.

**Comment by ankurs-delphix** [comment]
@ahrens @nupur-agrawal-delphix 
I ran the complete suite again today with latest chages from the upstream project and all were passing. 

```
delphix@ip-10-110-239-115:/usr/share/zfs$ ./zfs-tests.sh -T functional -r object_store.run
Test: /usr/share/zfs/zfs-tests/tests/functional/acl/off/setup (run as root) [00:10] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/acl/off/posixmode (run as root) [00:01] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/acl/off/cleanup (run as root) [00:03] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix-sa/setup (run as root) [00:11] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix-sa/posix_001_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix-sa/posix_002_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix-sa/posix_003_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix-sa/posix_004_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix-sa/cleanup (run as root) [00:02] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix/setup (run as root) [00:10] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix/posix_001_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix/posix_002_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix/posix_003_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix/posix_004_pos (run as root) [00:00] [PASS]
Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/acl/posix/cleanup (run as root) [00:02] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/setup (run as root) [00:08] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/atime_001_pos (run as root) [00:14] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/atime_002_neg (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/atime_003_pos (run as root) [00:14] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/root_atime_off (run as root) [00:12] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/root_atime_on (run as root) [00:17] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/root_relatime_on (run as root) [00:17] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/atime/cleanup (run as root) [00:02] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/chattr/setup (run as root) [00:10] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/chattr/chattr_001_pos (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/chattr/chattr_002_neg (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/chattr/cleanup (run as root) [00:03] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs/setup (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs/zfs_001_neg (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs/zfs_002_pos (run as root) [00:11] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs/zfs_003_neg (run as root) [00:30] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs/cleanup (run as root) [00:01] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_bookmark/setup (run as root) [00:11] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_bookmark/zfs_bookmark_cliargs (run as root) [00:35] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_bookmark/cleanup (run as root) [00:03] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/setup (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key.ksh (run as root) [00:05] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_child.ksh (run as root) [00:13] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_clones.ksh (run as root) [00:18] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_format.ksh (run as root) [00:06] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_inherit.ksh (run as root) [00:08] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_load.ksh (run as root) [00:05] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_location.ksh (run as root) [00:04] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/zfs_change-key_pbkdf2iters.ksh (run as root) [00:05] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cli_root/zfs_change-key/cleanup (run as root) [00:02] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cp_files/setup (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cp_files/cp_files_001_pos (run as root) [03:57] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/cp_files/cleanup (run as root) [00:04] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/ctime/setup (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/ctime/ctime_001_pos (run as root) [00:49] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/ctime/cleanup (run as root) [00:02] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/exec/setup (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/exec/exec_001_pos (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/exec/exec_002_neg (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/exec/cleanup (run as root) [00:02] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/fallocate/setup (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/fallocate/fallocate_prealloc (run as root) [00:01] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/fallocate/fallocate_punch-hole (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/fallocate/cleanup (run as root) [00:03] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/mount/setup (run as root) [00:13] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/mount/umount_001 (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/mount/umountall_001 (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/mount/umount_unlinked_drain (run as root) [00:30] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/mount/cleanup (run as root) [00:02] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/suid/setup (run as root) [00:09] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/suid/suid_write_to_none (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/suid/suid_write_to_sgid (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/suid/suid_write_to_suid (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/suid/suid_write_to_suid_sgid (run as root) [00:00] [PASS]
Test: /usr/share/zfs/zfs-tests/tests/functional/suid/cleanup (run as root) [00:02] [PASS]
Results Summary
PASS	  70

Running Time:	00:12:22
Percent passed:	100.0%
Log directory:	/var/tmp/test_results/20210806T183307

Tests with results other than PASS that are expected:

Tests with result of PASS that are unexpected:

Tests with results other than PASS that are unexpected:
```

**Comment by ankurs-delphix** [comment]
Accidentally closed PR, hence reopening it again

**Pull request merged**
