### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by pzakha**
Resolving auto-merge failure:

https://github.com/delphix/zfs/commit/26b60474691ad4bdb91f61b667819e22aabc202f added new files we need to be added to our package lists.

### CODE REVIEW

**Comment by pzakha** [comment]
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/1741/

**Comment by ahrens** [comment]
For future reference, it's easier to review the conflict if you merge only the conflicting commit, i.e. `git merge <conflicting commit>` rather than `git merge origin/upstreams/master`.  The automatic merges will take over after the conflicting commit is manually merged.

**Comment by pzakha** [comment]
Yeah, I was thinking of doing that, but it would have required 2 manual merges:
1. A merge of all commits up until that commit.
2. A merge of this particular commit.

**Comment by ahrens** [comment]
> added new files we need to be added to our package lists
Will we always see a conflict when this happens, or could this kind of change (adding new files that need to be added to our package lists) be merged automatically (without conflicts) sometimes?  If the latter, we will want to keep an eye out for when these kind of changes go in upstream so that we can remember to add them to our package lists.

**Comment by ahrens** [comment]
@pzakha ah I see.  Typically that doesn't happen (it gets stuck on the conflicting commit) but because there was another conflict (the spacemap log), our repo got many commits behind master.  The auto merging script could be smarter about this (e.g. merging one commit at a time) but hopefully it isn't worth doing that because we'll have so few conflicts in the future 🤞

**Comment by pzakha** [comment]
> Will we always see a conflict when this happens...

Yeah, I believe so, since we need to manually decide which of the produced files go into which package.
There is an explicit check in the `rules` file: `dh_install --fail-missing`
This check ensures that all of the produced files are included in some packages.

**Comment by pzakha** [comment]
> The auto merging script could be smarter about this (e.g. merging one commit at a time)

This could be doable, but could be tricky, especially if we want to add integration testing in the mix. We can discuss this more offline if you are interested though.

**Comment by pzakha** [comment]
Pushed manually using git command. I've split the commit with conflicts into its own merge.

**Pull request closed without merging**
