### PR TITLE
DLPX-75316 [Backport of DLPX-71919 to 6.0.9.0] core dumped caused by GRUB after upgrade to 6.0.7.0/trunk (5.3.9.0-> 6.0.x -> 6.0.7.0/trunk)

### PR DESCRIPTION
**Pull request by pcd1193182**
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5426/

Clean cherry-pick from  master

### CODE REVIEW

**Comment by pzakha** [comment]
Looks like the build has failed

**Comment by pcd1193182** [comment]
> Looks like the build has failed

Indeed, the cherry-pick was clean but there was a build system change that I didn't account for. That's fixed in the latest version.

**Comment by pcd1193182** [comment]
The failure in the ab-pre-push run appears to be environmental? None of these changes should affect the storage of credentials in the Delphix Engine.

**Review by sebroy — APPROVED** [review]

**Review by pzakha — APPROVED** [review]
Could you re-run the tests? Given that this bug is for fixing an upgrade issue, it would be useful to have a clean upgrade run. Hopefully the environmental issues were transient.

**Comment by pcd1193182** [comment]
Yep, http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5445/ is in progress already.

**Comment by pcd1193182** [comment]
Looks like this run hit https://jira.delphix.com/browse/DLPX-59380 as well... I'll try another.
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5446/

**Pull request merged**
