### PR TITLE
Update libzfs and libzfs_core abi files

### PR DESCRIPTION
**Pull request by brad-lewis**
The abi check was failing due to divergence in our interfaces and those recorded in libzfs.abi and libzfs_core.abi.  I generated new files with the make storeabi target after installing libabigail-dev and abigail-tools packages.

### CODE REVIEW

**Comment by ahrens** [comment]
It seems pretty unfortunate that these machine-generated files have to be rewritten.  Since local changes cause the entire file to be generated differently (e.g. due to different ID numbers, but maybe other things as well), these might as well be binary blobs.  I'd be interested to hear from @behlendorf and @aerusso on this.  e.g. When does the OpenZFS project plan to update these files?  With each release?

**Comment by behlendorf** [comment]
@ahrens the plan of record is pretty conventional.  Each release branch (zfs-2.0-release, zfs-2.1-release, etc) will have a committed stable interface for the non-`libzpool` libraries. For each new MINOR OpenZFS release we'll have the opportunity to make non breaking changes, like adding an interface, and increase then library minor version accordingly.  OpenZFS MAJOR releases are our chance to make breaking changes like removing an interface or changing its arguments.  The abi files are simply a nice way for the CI catch any change before it sneaks in and causes an us to accidentally break the versioned library ABI.  These checks are now being run by the CI on PRs.

**Comment by ahrens** [comment]
@behlendorf When there's a PR against OpenZFS (master branch) that adds a new interface to a library, the submitter should bump the library version, regenerate the .abi files, and include them as part of the PR?

**Comment by behlendorf** [comment]
@ahrens yes, if the ABI is being changed intentionally then we'll want to include an updated `.abi` file for that library in the PR.  As for bumping the library version that's something we'll definitely need to do for the next release branch.  But we may want to hold off bumping the version until just before branching the release in order to batch up all the library changes.  Though hopefully there aren't to many.

**Comment by brad-lewis** [comment]
Holding off on this as per Brian's comment above.

**Pull request closed without merging**
