### PR TITLE
fix merge conflict

### PR DESCRIPTION
**Pull request by grwilson**
```gwilson@George-Wilsons-MacBook-Pro zfs-merge % git diff
diff --cc include/libzfs.h
index 25fd6128c,5f0bc03be..000000000
--- a/include/libzfs.h
+++ b/include/libzfs.h
@@@ -912,8 -914,19 +914,24 @@@ int zfs_smb_acl_rename(libzfs_handle_t
  extern int zpool_enable_datasets(zpool_handle_t *, const char *, int);
  extern int zpool_disable_datasets(zpool_handle_t *, boolean_t);
 + i/libzfs.h

++<<<<<<< HEAD
 +extern int zfs_get_hole_count(const char *, uint64_t *, uint64_t *);
 +extern int zfs_get_access_info(const char *, zfs_access_info_t *);
++=======
+ /*
+  * Parse a features file for -o compatibility
+  */
+ typedef enum {
+       ZPOOL_COMPATIBILITY_OK,
+       ZPOOL_COMPATIBILITY_READERR,
+       ZPOOL_COMPATIBILITY_BADFILE,
+       ZPOOL_COMPATIBILITY_BADWORD,
+       ZPOOL_COMPATIBILITY_NOFILES
+ } zpool_compat_status_t;
+
+ extern zpool_compat_status_t zpool_load_compat(const char *,
+     boolean_t *, char *, char *);
++>>>>>>> bedbc13daa6dfe9e0221bfadb8d8db2378deaacc

  #ifdef __FreeBSD__
```

Added by commit:
```commit 658fb8020f0501435516baeea7004575d640649b
Author: Colm <colm@tuatha.org>
Date:   Thu Feb 18 05:30:45 2021 +0000

    Add "compatibility" property for zpool feature sets

    Property to allow sets of features to be specified; for compatibility
    with specific versions / releases / external systems. Influences
    the behavior of 'zpool upgrade' and 'zpool create'. Initial man
    page changes and test cases included.
```

### CODE REVIEW

**Comment by grwilson** [comment]
ab-pre-push: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4853/

**Review by ahrens — APPROVED** [review]

**Review by pcd1193182 — APPROVED** [review]

**Comment by grwilson** [comment]
Also needed to add the following for our debian package:

```
gwilson@George-Wilsons-MacBook-Pro zfs-merge % git diff
diff --git a/debian/zfsutils-linux.install b/debian/zfsutils-linux.install
index a7fa1e398..85c1d484f 100644
--- a/debian/zfsutils-linux.install
+++ b/debian/zfsutils-linux.install
@@ -120,3 +120,4 @@ usr/share/man/man8/fsck.zfs.8
 usr/share/man/man8/zfs-program.8
 usr/share/man/man8/zgenhostid.8
 usr/share/man/man8/zfs-mount-generator.8
+usr/share/zfs/compatibility.d/
```

**Comment by grwilson** [comment]
I am also fixing an ENUM failure on the appstack and will post the review here shortly. The latest ab-pre-push is: http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/4870/

**Review by pzakha — APPROVED** [review]

**Comment by grwilson** [comment]
Appstack change required: http://reviews.delphix.com/r/66698/

**Pull request merged**
