### PR TITLE
Disable "-fipa-sra" when using "--enable-debuginfo"

### PR DESCRIPTION
**Pull request by prakashsurya**
To better enable dynamic tracing tools (e.g. "bpftrace") this change
disables the "-fipa-sra" compilation optimization. This way, function
signatures are not changed by the compiler, which allows us to better
attach to kprobes and kretprobes with dynamic tracing tools. Otherwise,
the compiler may append ".isra" to the function name, and possibly
change the function arguments as well.

### CODE REVIEW

**Comment by prakashsurya** [comment]
- `git-ab-pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/2790/)
- `git-zfs-precommit` is [here](http://platform.jenkins.delphix.com/job/devops-gate/job/master/job/zfs-precommit/5044/)
- Upstream PR is here: https://github.com/zfsonlinux/zfs/pull/9921

**Comment by prakashsurya** [comment]
Without this change, we can see some functions contain the `.isra` suffix:
```
$ sudo bpftrace -l | grep metaslab_group_alloc
kprobe:metaslab_group_allocatable
kprobe:metaslab_group_alloc_increment.isra.12
kprobe:metaslab_group_alloc_update
kprobe:metaslab_group_alloc_decrement
kprobe:metaslab_group_alloc_verify
kprobe:metaslab_group_alloc_normal.isra.15
kprobe:metaslab_group_alloc.isra.16
```

With this change, none of those functions have the `.isra` suffix anymore:
```
$ sudo bpftrace -l | grep metaslab_group_alloc
kprobe:metaslab_group_allocatable
kprobe:metaslab_group_alloc_increment
kprobe:metaslab_group_alloc_update
kprobe:metaslab_group_alloc_decrement
kprobe:metaslab_group_alloc_verify
kprobe:metaslab_group_alloc_normal
kprobe:metaslab_group_alloc
```

**Comment by prakashsurya** [comment]
I'll defer to the performance team to answer that; @tonynguien can you comment on the question above?

**Comment by ahrens** [comment]
This seems like something that we could reasonably propose for upstream as well.

**Comment by prakashsurya** [comment]
Agreed; I've opened a PR upstream and linked to it in my comment above. I wasn't sure how upstream would feel about this, so I opened both upstream and downstream PRs; this one can be closed if the upstream PR gains traction.

**Comment by prakashsurya** [comment]
Closing as this landed upstream, and has been merged with our downstream master branch: https://github.com/delphix/zfs/commit/147622b2f1e5d8c51b1aeb4735d5e0fa5c91ff78

**Pull request closed without merging**
